language: r

r:
  - bioc-devel
  - bioc-release

# Strict checks in place
warnings_are_errors: false

cache:
  - packages: true

#branches:
#  only:
#    - master
before_install:
  - sudo apt-get -y install libmagick++-dev

r_github_packages:
  - jimhester/covr
  
notifications:
  email:
    recipients:
      - cvallejos@turing.ac.uk 
    on_success: change # default: change
    on_failure: always # default: always

after_success:
  - Rscript -e 'library(covr); codecov()'
